services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard-haskell-react-backend
    ports:
      - "8005:8005"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8005/api
    container_name: dashboard-haskell-react-frontend
    ports:
      - "3005:80"
    restart: unless-stopped
